import React from 'react';
import QueryProvider from '@/utils/QueryProvider';

export const metadata = {
  title: 'PIMSmart',
  // description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
